# Generated by Django 3.2.7 on 2021-11-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('hockey', 'Hockey'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('football', 'Football'), ('soccer', 'Soccer')], default='hockey', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
